### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by Gabriel-p** [liquid-phynix/okular-session-restore#1]
Hi there! I found your script looking for a way to save and restore a session in Okular. I usually have several tabs opened, and there's currently no way to save this list within Okular.

Are there any instructions available on how your script works?

Cheers.

PD: I am aware that this is an old script. Just checking if you might have something already written stored somewhere.

**Comment by liquid-phynix** [comment]
Hello Gabriel,

I haven't been using okular for quite a while now, I didn't even know it supports tabs.
The script worked like this: it subscribes to a DBus event and checks if this event originates from okular. Okular announces this event when closes or opens a document. So this script keeps an up-to-date list of the documents open in okular. When the script quits, it saves this list to a file, or when it starts up, it loads the files mentioned in the list with okular. I have no idea if this still works, you should try it out.

If you have further questions, just ask. I remember I used some dbus monitoring application to find out, what the relevant messages were... but this was a long time ago.

**Comment by Gabriel-p** [comment]
Thank you @liquid-phynix, I'll see if I can adapt it to the new Okular when I have some time.
Cheers!
